'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the summation of the even-valued terms.
'''
def fibonacchi(n):
    x =1
    y = 1
    summation = 0
    while(y < n):
        z = x + y
        x = y
        y = z
        if(y%2 == 0):
            summation = summation + z
    
    return summation

print(fibonacchi(4000000))